name : micro-service-user

services:
  # PostgreSQL para User Service
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #  User Service
  user-service:
    image: user-service:1.0
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://localhost:5432/userdb
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=postgres
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge
volumes:
  postgres-user-data:
    driver: local